# Generated by Django 5.0.7 on 2024-10-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloog', '0003_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='subjects',
            new_name='subject',
        ),
    ]
