# Generated by Django 5.0.7 on 2024-10-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloog', '0004_rename_subjects_ticket_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='subject',
            new_name='subjects',
        ),
    ]
