# Generated by Django 5.0.7 on 2024-10-13 15:58

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloog', '0005_rename_subject_ticket_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکتها'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name=' نام')),
                ('body', models.TextField(verbose_name='پیام')),
                ('publish', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ناریخ تولید')),
                ('active', models.BooleanField(default=True, verbose_name=' فعالیت')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bloog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'کامنت ',
                'verbose_name_plural': ' کامنت ها',
            },
        ),
    ]
