# Generated by Django 5.0.7 on 2024-10-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloog', '0006_alter_ticket_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(default='14', verbose_name='زمان مطالعه'),
        ),
    ]
