# Generated by Django 5.0.7 on 2024-10-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloog', '0008_alter_comment_create_alter_comment_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='شماره'),
        ),
    ]
