# Generated by Django 5.0.7 on 2024-10-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloog', '0010_alter_post_create_alter_post_publish_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagefield',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
    ]
