# Generated by Django 5.0.7 on 2024-10-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloog', '0011_alter_imagefield_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefield',
            old_name='image_file',
            new_name='image_filed',
        ),
    ]
