# Generated by Django 5.0.7 on 2024-10-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloog', '0012_rename_image_file_imagefield_image_filed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefield',
            old_name='image_filed',
            new_name='image_file',
        ),
    ]
