# Generated by Django 5.0.7 on 2024-10-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloog', '0013_rename_image_filed_imagefield_image_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagefield',
            options={'ordering': ['-create'], 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AlterField(
            model_name='imagefield',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ناریخ تولید'),
        ),
        migrations.AddIndex(
            model_name='imagefield',
            index=models.Index(fields=['create'], name='bloog_image_create_c7ad43_idx'),
        ),
    ]
